# Generated by Django 3.1.5 on 2021-02-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=1)),
                ('start_date', models.TimeField()),
                ('checkout', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.timeslot'),
            preserve_default=False,
        ),
    ]
