# Generated by Django 3.1.5 on 2021-02-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20210203_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='start_date',
            new_name='checkin',
        ),
    ]
