# Generated by Django 3.1.5 on 2021-02-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_auto_20210205_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='checkin',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='timeslot',
            old_name='checkout',
            new_name='check_out',
        ),
    ]
