# Generated by Django 3.1.5 on 2021-02-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_auto_20210205_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
