# Generated by Django 3.1.5 on 2021-02-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_auto_20210211_1842'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timeslot',
            name='unique_timeslo',
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('check_in', 'check_out'), name='unique_timeslot'),
        ),
    ]
