# Generated by Django 3.1.5 on 2021-03-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_auto_20210211_1843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('day', 'time_slot', 'asset', 'customer'), name='unique_booking'),
        ),
    ]
