# Generated by Django 3.1.5 on 2021-03-14 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingapp', '0010_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profile',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('day', 'time_slot', 'asset', 'user'), name='unique_booking'),
        ),
    ]
