# Generated by Django 3.1.5 on 2021-03-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_auto_20210314_1507'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('day', 'time_slot', 'asset'), name='unique_booking'),
        ),
    ]
